# Generated by Django 4.0.2 on 2022-04-15 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('creacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MiniPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('miniPlanta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictivo_offline.miniplanta')),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val_vibracion', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('val_ultSonido', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('fechaMedicion', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictivo_offline.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictivo_offline.sector'),
        ),
    ]
