# Generated by Django 4.0.2 on 2022-04-16 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predictivo_offline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='usuario',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
            preserve_default=b'I01\n',
        ),
    ]
