# Generated by Django 4.0.2 on 2022-04-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictivo_offline', '0002_medicion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='punto',
            field=models.CharField(blank=b'I01\n', max_length=1, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
