# Generated by Django 4.0.2 on 2022-04-17 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictivo_offline', '0003_equipo_punto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='punto',
        ),
        migrations.RemoveField(
            model_name='medicion',
            name='equipo',
        ),
        migrations.AddField(
            model_name='medicion',
            name='fechaRegistro',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='fechaMedicion',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='PuntoMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punto', models.CharField(max_length=1)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictivo_offline.componente')),
            ],
        ),
        migrations.AddField(
            model_name='componente',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictivo_offline.equipo'),
        ),
        migrations.AddField(
            model_name='medicion',
            name='punto',
            field=models.ForeignKey(blank=b'I01\n', null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='predictivo_offline.puntomedicion'),
            preserve_default=b'I01\n',
        ),
    ]
