# Generated by Django 4.0.2 on 2022-04-17 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictivo_offline', '0004_componente_remove_equipo_punto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='punto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictivo_offline.puntomedicion'),
        ),
    ]
